### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by RoboMWM** [TechFortress/GriefPrevention-Docs#1]
I want this to work similarly to the github wiki where pages show up automatically in a sidebar or something, and is a very simple, responsive layout, and parses markdown into HTML.

Idk jekyll themes but when I was browsing like a month ago none worked as well as I'd like, idk.

While I'm open to stuff like readthedocs, I highly prefer something that can be run by github pages so I don't have to deal with another service/account.

**Comment by Jikoo** [comment]
I've been looking into this recently due to frustration with the limitations of GH's wiki system (no automatic TOC generation, forced either fully public or limited to collaborators, etc.) and stumbled on [just-the-docs](https://github.com/pmarsceill/just-the-docs), which appears to be a very clean Jekyll theme. Search, sidebar (not sure about automatic page inclusion, I don't think so just because of the collapsible nav list), TOC generation, and quite pretty.

**Comment by RoboMWM** [comment]
Thanks! Not sure if I stumbled across this before or not but will give it a shot.

**Comment by RoboMWM** [comment]
ayyy, they do. https://pmarsceill.github.io/just-the-docs/docs/configuration/#document-collections

**Comment by RoboMWM** [comment]
idk what the heccin im doin with collections but the moment I put it in the entire nav just disappears
 hecciasndf;lasdjf

**Comment by RoboMWM** [comment]
Ok, so it does not exactly what I wanted. I wanted it to automatically generate child pages. Whatever. Frontmatter it is then. https://i.imgur.com/ZWF4Vt3.png

**Comment by Jikoo** [comment]
Ah bummer, thought it did based on the writeup. Oh well
